# DEPLOYMENT
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  # Name
  name: backend
  # Labels
  labels:
    app: wordpress
    tier: backend
# POD
spec:
  replicas: 1
  selector:
    # Nodes that match labels
    matchLabels:
      app: wordpress
      tier: backend
  strategy:
    type: RollingUpdate
  template:
    metadata:
      # Labels
      labels:
        app: wordpress
        tier: backend
    spec:
      containers:
        # Image
        - image: ajuthaya/nginx-php
          # Name
          name: backend-pod
          # Environment variables
          env:
            # MYSQL: Host
            - name: WORDPRESS_DB_HOST
              value: database
            # MYSQL: Database
            - name: WORDPRESS_DB
              valueFrom:
                secretKeyRef:
                  name: passwords
                  key: MYSQL_DATABASE
            # MYSQL: Username
            - name: WORDPRESS_DB_USER
              valueFrom:
                secretKeyRef:
                  name: passwords
                  key: MYSQL_USER
            # MYSQL: Password
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: passwords
                  key: MYSQL_PASSWORD
          # Map exposed ports
          ports:
            - containerPort: 80
              name: wordpress
          # Mount volume locations
          volumeMounts:
            - name: wordpress-persistent-volume
              mountPath: /opt/app/aj_portfolio/data/wordpress
            - name: wordpress-config
              mountPath: /opt/app/aj_portfolio/config/wordpress
          # Run on startup
          lifecycle:
            postStart:
              exec:
                command: [
                  "/bin/sh",
                  "-c",
                  # Clone project
                  # Copy config into project folder
                  # Clean out nginx view folder
                  # Copy project into nginx view folder
                  "git clone https://github.com/AjUthaya/aj_portfolio-backend-wordpress.git /opt/app/aj_portfolio/backend &&
                  cp /opt/app/aj_portfolio/config/wordpress/wp-config.php /opt/app/aj_portfolio/backend/wp-config.php &&
                  rm -R /usr/share/nginx/html/* &&
                  cp -R /opt/app/aj_portfolio/backend/* /usr/share/nginx/html",
                ]
      # Connect volumes
      volumes:
        # WordPress Uploads
        - name: wordpress-persistent-volume
          persistentVolumeClaim:
            claimName: wordpress-pvc
        # WORDPRESS CONFIG
        - name: wordpress-config
          secret:
            secretName: wordpress
            items:
              - key: config
                path: wp-config.php

---
# SERVICE
apiVersion: v1
kind: Service
metadata:
  # Name
  name: backend
  # Labels
  labels:
    app: wordpress
    tier: backend
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
  selector:
    app: wordpress
    tier: backend
