# DEPLOYMENT
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  # Name
  name: backend
  # Labels
  labels:
    app: wordpress
    tier: backend
# POD
spec:
  replicas: 2
  selector:
    # Select nodes
    matchLabels:
      app: wordpress
      tier: backend
  strategy:
    type: RollingUpdate
  template:
    metadata:
      # Labels
      labels:
        app: wordpress
        tier: backend
    spec:
      # Volumes
      volumes:
        # WordPress Uploads
        - name: wordpress-persistent-volume
          persistentVolumeClaim:
            claimName: wordpress-pvc
        # WordPress config
        - name: wordpress-config
          secret:
            secretName: backend
            items:
              - key: config
                path: wp-config.php
      # Containers
      containers:
        # Image
        - image: ajuthaya/nginx-php
          name: backend-pod
          # Resources
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 250Mi
          # Mount volumes
          volumeMounts:
            - name: wordpress-persistent-volume
              mountPath: /opt/app/aj_portfolio/data/wordpress
            - name: wordpress-config
              mountPath: /opt/app/aj_portfolio/config/wordpress
          # Map ports
          ports:
            - containerPort: 80
              name: wordpress
          # Environment variables
          env:
            # MYSQL: Host
            - name: WORDPRESS_DB_HOST
              value: database
            # MYSQL: Database
            - name: WORDPRESS_DB
              valueFrom:
                secretKeyRef:
                  name: passwords
                  key: MYSQL_DATABASE
            # MYSQL: Username
            - name: WORDPRESS_DB_USER
              valueFrom:
                secretKeyRef:
                  name: passwords
                  key: MYSQL_USER
            # MYSQL: Password
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: passwords
                  key: MYSQL_PASSWORD
          # Run on startup
          lifecycle:
            postStart:
              exec:
                command: [
                  "/bin/sh",
                  "-c",
                  # Clone project
                  # Copy wordpress config into project folder
                  # Clean out nginx view folder
                  # Copy project into nginx view folder
                  # Link uploaded files
                  # Change owner of uploaded files
                  "git clone https://github.com/AjUthaya/aj_portfolio-backend-wordpress.git /opt/app/aj_portfolio/backend &&
                  cp /opt/app/aj_portfolio/config/wordpress/wp-config.php /opt/app/aj_portfolio/backend/wp-config.php &&
                  rm -R /usr/share/nginx/html/* &&
                  cp -R /opt/app/aj_portfolio/backend/* /usr/share/nginx/html &&
                  ln -s /opt/app/aj_portfolio/data/wordpress/uploads /usr/share/nginx/html/wp-content &&
                  chown -R www-data:www-data /usr/share/nginx/html",
                ]

---
# SERVICE
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: wordpress
    tier: backend
spec:
  # Request handler
  type: LoadBalancer
  # Select pods
  selector:
    app: wordpress
    tier: backend
  # Map ports
  ports:
    - port: 80
      nodePort: 30001
      targetPort: 80

