##### MYSQL #####
# DEPLOYMENT
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  # Name
  name: mysql-deployment
  # Labels
  labels:
    app: mysql
    tier: database
# POD
spec:
  replicas: 1
  selector:
    # Nodes that match labels
    matchLabels:
      app: mysql
      tier: database
  strategy:
    type: RollingUpdate
  template:
    metadata:
      # Labels
      labels:
        app: mysql
        tier: database
    spec:
      containers:
        # Image
        - image: mysql:5.6
          # Name
          name: mysql-pod
          # Environment variables
          env:
            # MYSQL: Root Password
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: env
                  key: MYSQL_ROOT_PASSWORD
            # MYSQL: Database
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: env
                  key: MYSQL_DATABASE
            # MYSQL: Username
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: env
                  key: MYSQL_USER
            # MYSQL: Password
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: env
                  key: MYSQL_PASSWORD
          # Map exposed ports
          ports:
            - containerPort: 3306
          # Mount volume locations
          volumeMounts:
            - name: mysql-persistent-volume
              mountPath: /var/lib/mysql
      # Connect persistent volumes
      volumes:
        - name: mysql-persistent-volume
          persistentVolumeClaim:
            claimName: mysql-pvc

---
# SERVICE
apiVersion: v1
kind: Service
metadata:
  # Name
  name: mysql-service
  # Labels
  labels:
    app: mysql
    tier: database
spec:
  selector:
    app: mysql
    tier: database
  clusterIP: None
##### MYSQL #####
#
#
#
#
#
---
##### NGINX #####
# DEPLOYMENT
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  # Name
  name: nginx-deployment
  # Labels
  labels:
    app: nginx
    tier: backend
# POD
spec:
  replicas: 1
  selector:
    # Nodes that match labels
    matchLabels:
      app: nginx
      tier: backend
  strategy:
    type: RollingUpdate
  template:
    metadata:
      # Labels
      labels:
        app: nginx
        tier: backend
    spec:
      containers:
        # Image
        - image: nginx:1.15
          # Name
          name: nginx-pod
          # Map exposed ports
          ports:
            - containerPort: 80
          # Mount volume locations
          volumeMounts:
            - name: app-persistent-volume
              mountPath: /opt/app/aj_portfolio/backend
            - name: nginx-config
              mountPath: /opt/config
          # Run on startup
          lifecycle:
            postStart:
              exec:
                command:
                  [
                    "/bin/sh",
                    "-c",
                    "cp /opt/config/default.conf /etc/nginx/conf.d/default.conf",
                  ]
      # Connect persistent volumes
      volumes:
        - name: app-persistent-volume
          persistentVolumeClaim:
            claimName: app-backend-pvc
        - name: nginx-config
          configMap:
            name: config
            items:
              - key: nginx
                path: default.conf

---
# SERVICE
apiVersion: v1
kind: Service
metadata:
  # Name
  name: nginx-service
  # Labels
  labels:
    app: nginx
    tier: backend
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
  selector:
    app: nginx
    tier: backend
##### NGINX #####
#
#
#
#
#
