##### MYSQL #####
# DEPLOYMENT
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  # Name
  name: database-deployment
  # Labels
  labels:
    app: mysql
    tier: database
# POD
spec:
  replicas: 1
  selector:
    # Nodes that match labels
    matchLabels:
      app: mysql
      tier: database
  strategy:
    type: RollingUpdate
  template:
    metadata:
      # Labels
      labels:
        app: mysql
        tier: database
    spec:
      containers:
        # Image
        - image: mysql:5.6
          # Name
          name: database-pod
          # Environment variables
          env:
            # MYSQL: Root Password
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: ROOT_PASSWORD
            # MYSQL: Database
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: DATABASE
            # MYSQL: Username
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: USER
            # MYSQL: Password
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: PASSWORD
          # Map exposed ports
          ports:
            - containerPort: 3306
          # Mount volume locations
          volumeMounts:
            - name: mysql-persistent-volume
              mountPath: /var/lib/mysql
      # Connect persistent volumes
      volumes:
        - name: mysql-persistent-volume
          persistentVolumeClaim:
            claimName: mysql-pvc

---
# SERVICE
apiVersion: v1
kind: Service
metadata:
  # Name
  name: database-service
  # Labels
  labels:
    app: mysql
    tier: database
spec:
  selector:
    app: mysql
    tier: database
  clusterIP: None
##### MYSQL #####
#
#
#
#
#
---
##### NGINX #####
# DEPLOYMENT
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  # Name
  name: backend-deployment
  # Labels
  labels:
    app: nginx
    tier: backend
# POD
spec:
  replicas: 1
  selector:
    # Nodes that match labels
    matchLabels:
      app: nginx
      tier: backend
  strategy:
    type: RollingUpdate
  template:
    metadata:
      # Labels
      labels:
        app: nginx
        tier: backend
    spec:
      containers:
        # Image
        - image: ajuthaya/nginx-php
          # Name
          name: backend-pod
          # Map exposed ports
          ports:
            - containerPort: 80
          # Mount volume locations
          volumeMounts:
            - name: wordpress-persistent-volume
              mountPath: /opt/app/aj_portfolio/data/wordpress
            - name: nginx-config
              mountPath: /opt/app/aj_portfolio/config/nginx
            - name: wordpress-config
              mountPath: /opt/app/aj_portfolio/config/wordpress
          # Run on startup
          lifecycle:
            postStart:
              exec:
                command: [
                    "/bin/sh",
                    "-c",
                    # Copy nginx config
                    # Clone project
                    # Copy config into project folder
                    # Clean out nginx view folder
                    # Copy project into nginx view folder
                    "cp /opt/app/aj_portfolio/config/nginx/default.conf /etc/nginx/conf.d/default.conf &&
                    git clone https://github.com/AjUthaya/aj_portfolio-backend-wordpress.git /opt/app/aj_portfolio/backend &&
                    cp /opt/app/aj_portfolio/config/wordpress/wp-config.php /opt/app/aj_portfolio/backend/wp-config.php &&
                    rm -R /usr/share/nginx/html/* &&
                    cp -R /opt/app/aj_portfolio/backend/* /usr/share/nginx/html",
                  ]
      # Connect persistent volumes
      volumes:
        # WordPress Uploads
        - name: wordpress-persistent-volume
          persistentVolumeClaim:
            claimName: wordpress-pvc
        # NGINX CONFIG
        - name: nginx-config
          configMap:
            name: nginx
            items:
              - key: config
                path: default.conf
        # WORDPRESS CONFIG
        - name: wordpress-config
          secret:
            secretName: wordpress
            items:
              - key: config
                path: wp-config.php

---
# SERVICE
apiVersion: v1
kind: Service
metadata:
  # Name
  name: backend-service
  # Labels
  labels:
    app: nginx
    tier: backend
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
  selector:
    app: nginx
    tier: backend
##### NGINX #####
