# DEPLOYMENT
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  # Name
  name: database
  # Labels
  labels:
    app: mysql
    tier: database
# POD
spec:
  replicas: 1
  selector:
    # Nodes that match labels
    matchLabels:
      app: mysql
      tier: database
  strategy:
    type: RollingUpdate
  template:
    metadata:
      # Labels
      labels:
        app: mysql
        tier: database
    spec:
      # Volumes
      volumes:
        # MYSQL persistent storage
        - name: mysql-persistent-volume
          persistentVolumeClaim:
            claimName: mysql-pvc
        # Init SQL file
        - name: mysql-config
          secret:
            secretName: database
            items:
              - key: config
                path: aj_portfolio.sql
      # Containers
      containers:
        # Image
        - image: mysql:5.7
          name: database-pod
          # Resources
          resources:
            #limits:
            #  cpu: 500m
            #  memory: 500Mi
            #requests:
            #  cpu: 250m
            #  memory: 250Mi
          # Mount volumes
          volumeMounts:
            - name: mysql-persistent-volume
              mountPath: /var/lib/mysql
              #mountPath: /opt/app/mysql
            - name: mysql-config
              mountPath: /opt/app/aj_portfolio/config/mysql
          # Map ports
          ports:
            - containerPort: 3306
              name: mysql
          # ENV
          env:
            # ENV: MYSQL
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: passwords
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: passwords
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: passwords
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: passwords
                  key: MYSQL_PASSWORD

---
# SERVICE
apiVersion: v1
kind: Service
metadata:
  name: database
  labels:
    app: mysql
    tier: database
spec:
  # Select pods
  selector:
    app: mysql
    tier: database
  # Map ports
  ports:
    - port: 3306
  clusterIP: None
