# DEPLOYMENT
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  # Name
  name: frontend
  # Labels
  labels:
    app: react
    tier: frontend
# POD
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    # Nodes that match labels
    matchLabels:
      app: react
      tier: frontend
  template:
    metadata:
      # Labels
      labels:
        app: react
        tier: frontend
    spec:
      # Volumes
      volumes:
        - name: frontend-config
          secret:
            secretName: frontend
            items:
              - key: config
                path: local.js
      # Containers
      containers:
        # Image
        - image: ajuthaya/nginx-node
          imagePullPolicy: Always
          name: frontend-pod
          # Resources
          resources:
            #limits:
            #  cpu: 500m
            #  memory: 500Mi
            #requests:
            #  cpu: 250m
            #  memory: 250Mi
          # Mount volumes
          volumeMounts:
            - name: frontend-config
              mountPath: /opt/app/aj_portfolio/config/react
          # Map ports
          ports:
            - containerPort: 80
              name: react
          # Readiness
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 5
          # Liveness
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 60
            timeoutSeconds: 15
            periodSeconds: 60
          # Startup commands
          lifecycle:
            postStart:
              exec:
                command: [
                  "/bin/sh",
                  "-c",
                  # Clone project
                  # Copy config into project folder
                  # Install production packages only
                  # Build project
                  # Copy build into nginx view folder
                  "git clone https://github.com/AjUthaya/aj_portfolio-frontend-react.git /opt/app/aj_portfolio/frontend &&
                  cp /opt/app/aj_portfolio/config/react/local.js /opt/app/aj_portfolio/frontend/src/local.js &&
                  cd /opt/app/aj_portfolio/frontend &&
                  npm install --production &&
                  npm run build &&
                  rm -R /usr/share/nginx/html/* &&
                  cp -R /opt/app/aj_portfolio/frontend/build/* /usr/share/nginx/html"
                ]

---
# SERVICE
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: react
    tier: frontend
spec:
  # Request handler
  type: LoadBalancer
  # Select pods
  selector:
    app: react
    tier: frontend
  # Map ports
  ports:
    - port: 80
      nodePort: 30000
      targetPort: 80
