# DEPLOYMENT
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  # Name
  name: frontend
  # Labels
  labels:
    app: react
    tier: frontend
# POD
spec:
  replicas: 1
  selector:
    # Nodes that match labels
    matchLabels:
      app: react
      tier: frontend
  strategy:
    type: RollingUpdate
  template:
    metadata:
      # Labels
      labels:
        app: react
        tier: frontend
    spec:
      containers:
        # Image
        - image: ajuthaya/nginx-node
          # Name
          name: frontend-pod
          # Map exposed ports
          ports:
            - containerPort: 80
              name: react
          # Mount volume locations
          volumeMounts:
            - name: frontend-config
              mountPath: /opt/app/aj_portfolio/config/react
          # Run on startup
          lifecycle:
            postStart:
              exec:
                command: [
                  "/bin/sh",
                  "-c",
                  # Clone project
                  # Copy config into project folder
                  # Install npm packages
                  # Build project
                  # Copy build into nginx view folder
                  "git clone https://github.com/AjUthaya/aj_portfolio-frontend-react.git /opt/app/aj_portfolio/frontend &&
                  cp /opt/app/aj_portfolio/config/react/local.js /opt/app/aj_portfolio/frontend/src/local.js &&
                  cd /opt/app/aj_portfolio/frontend && npm install &&
                  npm run build &&
                  rm -R /usr/share/nginx/html/* &&
                  cp -R /opt/app/aj_portfolio/frontend/build/* /usr/share/nginx/html",
                ]
      # Connect volumes
      volumes:
        # REACT CONFIG
        - name: frontend-config
          secret:
            secretName: frontend
            items:
              - key: config
                path: local.js

---
# SERVICE
apiVersion: v1
kind: Service
metadata:
  # Name
  name: frontend
  # Labels
  labels:
    app: react
    tier: frontend
spec:
  type: LoadBalancer
  ports:
    - port: 80
      nodePort: 30000
      targetPort: 80
  selector:
    app: react
    tier: frontend
