##### WordPress Uploads #####
# PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # Name
  name: wordpress-pvc
  # Labels
  labels:
    app: wordpress
spec:
  # Access
  accessModes:
    - ReadWriteOnce
  # Resources
  resources:
    requests:
      storage: 5G
  storageClassName: do-block-storage

---
##### MYSQL #####
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # Name
  name: mysql-pvc
  # Labels
  labels:
    app: mysql
    tier: database
spec:
  # Access
  accessModes:
    - ReadWriteOnce
  # Resources
  resources:
    requests:
      storage: 5G
  storageClassName: do-block-storage
